// This file is generated by XcodeStringEnum. Please do *NOT* update it manually.
// As a common practice, swiftLint is disabled for generated files.
// swiftlint:disable all

import SwiftUI

/// Makes it a bit easier to type.
typealias XCS = XcodeStringKey

/// Generated by StringCatalogEnum, this enum contains all existing Strin Category keys.
enum XcodeStringKey: String, CaseIterable {

    // MARK: - The following cases should be manually replaced in your codebase.

    /// 'en': "A scenic stretch of California's coast known for its views, parks, and outdoor activities"
    case bigSureDesc = "BigSureDesc"
    /// 'en': "Alcatraz Island"
    case alcatrazAttraction2 = "AlcatrazAttraction2"
    /// 'en': "Alcatraz"
    case alcatraz = "Alcatraz"
    /// 'en': "An iconic suspension bridge and one of the most internationally recognized symbols of San Francisco"
    case goldenGateBridgeDesc = "GoldenGateBridgeDesc"
    /// 'en': "An island offering a glimpse into the prison that once held some of the United States' most notorious criminals."
    case alcatrazDesc = "AlcatrazDesc"
    /// 'en': "Big Sur"
    case bigSur = "BigSur"
    /// 'en': "Bixby Creek Bridge"
    case bigSurAttraction1 = "BigSurAttraction1"
    /// 'en': "Bridge Viewpoints"
    case goldenGateBridgeAttraction = "GoldenGateBridgeAttraction"
    /// 'en': "Cellhouse"
    case alcatrazAttraction1 = "AlcatrazAttraction1"
    /// 'en': "Golden Gate Bridge"
    case goldenGateBridge = "GoldenGateBridge"
    /// 'en': "McWay Falls"
    case bigSurAttraction3 = "BigSurAttraction3"
    /// 'en': "Offers some of the best views of San Francisco, providing a panoramic lookout over the city."
    case twinPeaksDesc = "TwinPeaksDesc"
    /// 'en': "Pfeiffer Beach"
    case bigSurAttraction2 = "BigSurAttraction2"
    /// 'en': "Twin Peaks Summit"
    case twinPeaksAttraction = "TwinPeaksAttraction"
    /// 'en': "Twin Peaks"
    case twinPeaks = "TwinPeaks"
    /// No localizations available
    case getTravelDestinations = "Get travel destinations"
    /// No localizations available
    case lldAttractions = " %lld Attractions:"
    /// No localizations available
    case travelDestinations = "Travel Destinations"
    /// No localizations available
    case welcomeToSanFrancisco = "Welcome to San Francisco"

    /// Usage: `SwiftUI.Text(XCS.yourStringCatalogKey.key)`
    var key: LocalizedStringKey { LocalizedStringKey(rawValue) }

    var string: String { NSLocalizedString(self.rawValue, comment: "Generated localization from String Catalog key: \(key)") }

    // var text: String.LocalizationValue { String.LocalizationValue(rawValue) }
}
// swiftlint:enable all