// This file is generated by XcodeStringEnum. Please do *NOT* update it manually.
// As a common practice, swiftLint is disabled for generated files.
// swiftlint:disable all

import SwiftUI

/// Makes it a bit easier to type.
typealias XCS = XcodeStringKey

/// Generated by StringCatalogEnum, this enum contains all existing Strin Category keys.
enum XcodeStringKey: String, CaseIterable {
    /// 'es': "Bienvenido de nuevo, %@"
    /// 'en': "Welcome Back, %@"
    case welcomeBack
    /// No localizations available
    case bets

    // MARK: - The following cases should be manually replaced in your codebase.

    /// 'es': "Después de una espera de 47 años, los Nuggets son campeones de la NBA después de una victoria en el Juego 5 contra el Heat en la que Nikola Jokic reclamó los honores de Jugador Más Valioso de las Finales de la NBA Bill Russell."
    case afterA47YearWaitTheNuggetsAreNbaChampsAfterAGame5WinVsTheHeatInWhichNikolaJokicClaimedBillRussellNbaFinalsMvpHonors = "After a 47-year wait, the Nuggets are NBA champs after a Game 5 win vs. the Heat in which Nikola Jokic claimed Bill Russell NBA Finals MVP honors."
    /// 'es': "Noticias de actualidad para el baloncesto 🏀"
    case trendingNewsForBasketball = "Trending News for Basketball 🏀"
    /// 'es': "Persiguiendo la historia: los Nuggets alcanzan la cima de la NBA (EP: 31)"
    case chasingHistoryNuggetsReachNbaSummitEp31 = "Chasing History: Nuggets reach NBA summit (EP: 31)"

    /// Usage: `SwiftUI.Text(XCS.yourStringCatalogKey.key)`
    var key: LocalizedStringKey { LocalizedStringKey(rawValue) }

    var string: String { NSLocalizedString(self.rawValue, comment: "Generated localization from String Catalog key: \(key)") }

    // var text: String.LocalizationValue { String.LocalizationValue(rawValue) }
}
// swiftlint:enable all