// This file is generated by XcodeStringEnum. Please do *NOT* update it manually.
// As a common practice, swiftLint is disabled for generated files.
// swiftlint:disable all

import SwiftUI

/// Makes it a bit easier to type.
typealias XCS = XcodeStringKey

/// Generated by StringCatalogEnum, this enum contains all existing Strin Category keys.
enum XcodeStringKey: String, CaseIterable {

    // MARK: - The following cases should be manually replaced in your codebase.

    /// 'en': "Hello, %@! Welcome to our app."
    case welcomeMessageFormat = "WelcomeMessageFormat"
    /// 'en': "This Content is for testing only"
    case testingKey = "TestingKey"
    /// 'en': "Welcome Back!"
    case welcomeBackKey = "WelcomeBackKey"
    /// 'en': "You are now have %d items."
    case multipleItemsMessage = "MultipleItemsMessage"
    /// 'en': "You are now have 1 item."
    case singleItemMessage = "SingleItemMessage"
    /// No localizations available
    case helloWorld = "Hello, world!"

    /// Usage: `SwiftUI.Text(XCS.yourStringCatalogKey.key)`
    var key: LocalizedStringKey { LocalizedStringKey(rawValue) }

    var string: String { NSLocalizedString(self.rawValue, comment: "Generated localization from String Catalog key: \(key)") }

    // var text: String.LocalizationValue { String.LocalizationValue(rawValue) }
}
// swiftlint:enable all